{{- $schedulerToken := .Values.authentication.scheduler.token | default (randAlphaNum 128) }}
{{- $clientToken := .Values.authentication.client.token | default (randAlphaNum 128) }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sccache.fullname" . }}-config
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  scheduler.conf: |
    # The socket address the scheduler will listen on. It's strongly recommended
    # to listen on localhost and put a HTTPS server in front of it.
    public_addr = "0.0.0.0:{{ .Values.scheduler.service.port }}"

    [client_auth]
    type = "token"
    token = "{{ $clientToken }}"
    #OAUTH
    # type = "oauth2_code_grant_pkce"
    # auth_url = "https://keycloak-qa.cern.ch/auth/realms/cern"
    # client_id = ""
    # token_url = ""
    # cache_secs = "3600"
    # required_groups = ["group_name"]

    [server_auth]
    type = "token"
    token = "{{ $schedulerToken }}"

  server.conf: |
    # This is where client toolchains will be stored.
    cache_dir = "/tmp/toolchains"
    # The maximum size of the toolchain cache, in bytes.
    # If unspecified the default is 10GB.
    # toolchain_cache_size = 10737418240
    # A public IP address and port that clients will use to connect to this builder.
    public_addr = "127.0.0.1:{{ .Values.server.service.port }}"
    # The URL used to connect to the scheduler (should use https, given an ideal
    # setup of a HTTPS server in front of the scheduler)
    scheduler_url = "http://{{ include "sccache.fullname" . }}-scheduler.{{ .Release.Namespace }}.svc.cluster.local:10600"

    [builder]
    type = "overlay"
    # The directory under which a sandboxed filesystem will be created for builds.
    build_dir = "/tmp/build"
    # The path to the bubblewrap version 0.3.0+ `bwrap` binary.
    bwrap_path = "/usr/bin/bwrap"

    [scheduler_auth]
    type = "token"
    token = "{{ $schedulerToken }}"
    # TODO: Generate jwt_token automatically
    # type = "jwt_token"
    # token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjAsInNlcnZlcl9pZCI6IjEyNy4wLjAuMToxMDUwMSJ9.1mgHVI9hLA8aM-rI6EjR1uapOpHi8y4r0LFStTpBTq8"

