apiVersion: v1
kind: Service
metadata:
  name: {{ include "sccache.fullname" . }}-scheduler
  labels:
    {{- include "sccache.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
  - port: {{ .Values.scheduler.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "sccache.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler